## Semantic analysis of the specification to identify the objects for the system
## Usually this means pick out the nouns :-)
## Adjectives will give clues about the Object fields, eg Failed papers

The requirement was to build a system to manage annual exams held in May each year. The system to be replaced was a manual one
using spreadsheets, paper forms and word documents. This system had a high administrative cost, was prone to error, and it was 
very difficult to produce summary reports.

Typically around 800 `candidates` worldwide sit for one of three `qualifications`. Qualifications may not be taken concurrently.
Each qualification requires multiple `papers` (between 2 to 5 depending on the qualification) to be passed before it can be awarded.
There is no requirement to sit all the papers in the same `exam period`, and a failed paper can be retaken any number of times. 

There are 35 exam `centres`, a centre can have more than one `venue`, so potentially hosting more than one exam at the same time. 
There is a strict exam `timetable` each year with exams timetabled to happen on the same day worldwide, at staggered 
times purely to respect regional time differences.

The CRM system (iMIS) is used to maintain Candidate details in an underlying SQL database. Exam candidates can be identified by 
a unique user `ID` and a user status of EXA in the iMIS NAME table. Information about each Candidates proper name, current address,
payment status etc needs to be sourced from here. Information to be maintained in the Exams system which extends the iMIS data
is `special requirements`, past exams taken, exams being taken this period, exam centre allocation.

Once papers are graded and mediated, the `marks` are entered into the system. The system "knows" the `rules` to apply and can determine 
whether the papers candidates have passed meet the qualification requirements, and at what grade - "Fail", "Pass", "Merit", "Distinction" 
